# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raiden.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0craiden.proto\x12\x1a\x61\x65\x61.brainbot.raiden.v0_0_1"\x9b\t\n\rRaidenMessage\x12]\n\rclose_channel\x18\x05 \x01(\x0b\x32\x44.aea.brainbot.raiden.v0_0_1.RaidenMessage.Close_Channel_PerformativeH\x00\x12Q\n\x07\x64\x65posit\x18\x06 \x01(\x0b\x32>.aea.brainbot.raiden.v0_0_1.RaidenMessage.Deposit_PerformativeH\x00\x12Q\n\x07\x66\x61ilure\x18\x07 \x01(\x0b\x32>.aea.brainbot.raiden.v0_0_1.RaidenMessage.Failure_PerformativeH\x00\x12[\n\x0copen_channel\x18\x08 \x01(\x0b\x32\x43.aea.brainbot.raiden.v0_0_1.RaidenMessage.Open_Channel_PerformativeH\x00\x12U\n\tstop_node\x18\t \x01(\x0b\x32@.aea.brainbot.raiden.v0_0_1.RaidenMessage.Stop_Node_PerformativeH\x00\x12Q\n\x07success\x18\n \x01(\x0b\x32>.aea.brainbot.raiden.v0_0_1.RaidenMessage.Success_PerformativeH\x00\x12S\n\x08transfer\x18\x0b \x01(\x0b\x32?.aea.brainbot.raiden.v0_0_1.RaidenMessage.Transfer_PerformativeH\x00\x1a\x62\n\x19Open_Channel_Performative\x12\x17\n\x0fpartner_address\x18\x01 \x01(\t\x12\x15\n\rtoken_address\x18\x02 \x01(\t\x12\x15\n\rtotal_deposit\x18\x03 \x01(\t\x1aL\n\x1a\x43lose_Channel_Performative\x12\x17\n\x0fpartner_address\x18\x01 \x01(\t\x12\x15\n\rtoken_address\x18\x02 \x01(\t\x1aV\n\x14\x44\x65posit_Performative\x12\x17\n\x0fpartner_address\x18\x01 \x01(\t\x12\x15\n\rtoken_address\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t\x1aW\n\x15Transfer_Performative\x12\x17\n\x0fpartner_address\x18\x01 \x01(\t\x12\x15\n\rtoken_address\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t\x1aM\n\x14Success_Performative\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x15\n\rdetail_is_set\x18\x03 \x01(\x08\x1aM\n\x14\x46\x61ilure_Performative\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x15\n\rdetail_is_set\x18\x03 \x01(\x08\x1a\x18\n\x16Stop_Node_PerformativeB\x0e\n\x0cperformativeb\x06proto3'
)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RAIDENMESSAGE._serialized_start = 45
    _RAIDENMESSAGE._serialized_end = 1224
    _RAIDENMESSAGE_OPEN_CHANNEL_PERFORMATIVE._serialized_start = 671
    _RAIDENMESSAGE_OPEN_CHANNEL_PERFORMATIVE._serialized_end = 769
    _RAIDENMESSAGE_CLOSE_CHANNEL_PERFORMATIVE._serialized_start = 771
    _RAIDENMESSAGE_CLOSE_CHANNEL_PERFORMATIVE._serialized_end = 847
    _RAIDENMESSAGE_DEPOSIT_PERFORMATIVE._serialized_start = 849
    _RAIDENMESSAGE_DEPOSIT_PERFORMATIVE._serialized_end = 935
    _RAIDENMESSAGE_TRANSFER_PERFORMATIVE._serialized_start = 937
    _RAIDENMESSAGE_TRANSFER_PERFORMATIVE._serialized_end = 1024
    _RAIDENMESSAGE_SUCCESS_PERFORMATIVE._serialized_start = 1026
    _RAIDENMESSAGE_SUCCESS_PERFORMATIVE._serialized_end = 1103
    _RAIDENMESSAGE_FAILURE_PERFORMATIVE._serialized_start = 1105
    _RAIDENMESSAGE_FAILURE_PERFORMATIVE._serialized_end = 1182
    _RAIDENMESSAGE_STOP_NODE_PERFORMATIVE._serialized_start = 1184
    _RAIDENMESSAGE_STOP_NODE_PERFORMATIVE._serialized_end = 1208
# @@protoc_insertion_point(module_scope)
